# data-raw/cox-demo-generator.R
# Frozen Cox demonstration dataset. Two arms (Standard care / New treatment),
# baseline age, and an ordinal stage (I/II/III). Engineered so age and stage
# confound the arm effect: the UNADJUSTED arm HR is near 1, but adjusting for
# age + stage reveals a protective adjusted HR (~0.6). Byte-reproducible; bump
# COX_DEMO.version on any change.
set.seed(73)
n <- 220
arm <- rep(c("Standard care", "New treatment"), each = n / 2)
age <- round(rnorm(n, 62, 9))
stage <- sample(c("I", "II", "III"), n, replace = TRUE, prob = c(0.4, 0.35, 0.25))
# Confounding: the New treatment arm skews older/sicker (channeling by indication).
sicker <- (arm == "New treatment")
age <- round(age + 5 * sicker)
stage_idx <- as.integer(factor(stage, levels = c("I", "II", "III")))
lp <- 0.05 * (age - 62) + 0.45 * (stage_idx - 1) - 0.55 * (arm == "New treatment")
time <- round(rexp(n, rate = 0.03 * exp(lp)) + 0.2, 1)
cens <- time > 36
time[cens] <- 36
status <- ifelse(cens, "Censored", "Death")

out <- data.frame(arm = arm, age = age, stage = stage,
                  followup_months = time, status = status,
                  stringsAsFactors = FALSE)
write.csv(out, "tests/testthat/fixtures/cox-demo.csv",
          row.names = FALSE, quote = FALSE)

rows_list <- lapply(seq_len(nrow(out)), function(i) as.list(out[i, ]))
rows_json <- jsonlite::toJSON(rows_list, auto_unbox = TRUE, digits = NA)
js <- paste0(
  "// GENERATED by data-raw/cox-demo-generator.R — do not hand-edit.\n",
  "export const COX_DEMO = {\n",
  '  version: "1.0.0",\n',
  '  label: "Synthetic demonstration data",\n',
  '  columns: ["arm", "age", "stage", "followup_months", "status"],\n',
  "  rows: ", rows_json, "\n};\n")
writeLines(js, "web/guided/cox/demo-data.js")
cat("md5(csv):", unname(tools::md5sum("tests/testthat/fixtures/cox-demo.csv")), "\n")
