# data-raw/explore-demo-generator.R
# Deterministic generator for the frozen Explore-plot demonstration dataset.
# Long format (one row per patient-visit) so the line geom's group role has
# repeated-measures data to bite on. ecog is DELIBERATELY numeric-coded (0/1/2)
# to exercise numeric-as-categorical handling; bmi has 5 fixed missing cells to
# exercise the complete-cases exclusion. Rerunning MUST reproduce the committed
# artifacts byte-for-byte; if you change anything, bump EXPLORE_DEMO.version.
set.seed(73)
n_pat <- 40
patient_id <- sprintf("P%02d", seq_len(n_pat))
arm <- rep(c("Control", "Treatment"), each = n_pat / 2)
sex <- sample(c("Female", "Male"), n_pat, replace = TRUE)
age <- round(rnorm(n_pat, mean = 62, sd = 10))
ecog <- sample(0:2, n_pat, replace = TRUE, prob = c(0.5, 0.35, 0.15))
bmi <- round(rnorm(n_pat, mean = 27, sd = 4), 1)
visits <- c(0, 3, 6)
base <- rlnorm(n_pat, meanlog = 3, sdlog = 0.4)
slope <- ifelse(arm == "Treatment", -0.18, -0.04)   # treatment lowers biomarker

idx <- rep(seq_len(n_pat), each = length(visits))
visit_month <- rep(visits, times = n_pat)
noise <- rlnorm(n_pat * length(visits), meanlog = 0, sdlog = 0.15)
biomarker <- round(base[idx] * exp(slope[idx] * visit_month) * noise, 1)

bmi_long <- bmi[idx]
miss_rows <- c(7, 31, 58, 84, 112)                  # fixed missing bmi cells
bmi_chr <- format(bmi_long, trim = TRUE)
bmi_chr[miss_rows] <- ""

out <- data.frame(
  patient_id = patient_id[idx], visit_month = visit_month,
  age = age[idx], bmi = bmi_chr, biomarker = biomarker,
  arm = arm[idx], sex = sex[idx], ecog = ecog[idx],
  stringsAsFactors = FALSE)
write.csv(out, "tests/testthat/fixtures/explore-demo.csv", row.names = FALSE, quote = FALSE)

rows_list <- lapply(seq_len(nrow(out)), function(i) {
  list(patient_id = out$patient_id[i], visit_month = out$visit_month[i],
       age = out$age[i], bmi = if (bmi_chr[i] == "") NA else bmi_long[i],
       biomarker = out$biomarker[i], arm = out$arm[i], sex = out$sex[i],
       ecog = out$ecog[i])
})
rows_json <- jsonlite::toJSON(rows_list, auto_unbox = TRUE, na = "null", digits = NA)
js <- paste0(
  "// GENERATED by data-raw/explore-demo-generator.R — do not hand-edit.\n",
  "export const EXPLORE_DEMO = {\n",
  '  version: "1.0.0",\n',
  '  label: "Synthetic demonstration data \\u2014 not for clinical use.",\n',
  '  columns: ["patient_id", "visit_month", "age", "bmi", "biomarker", "arm", "sex", "ecog"],\n',
  "  rows: ", rows_json, "\n};\n")
writeLines(js, "web/guided/explore/demo-data.js")
cat("md5(csv):", unname(tools::md5sum("tests/testthat/fixtures/explore-demo.csv")), "\n")
