# data-raw/groupcompare-demo-generator.R
# Deterministic generator for the frozen Group-comparison demonstration dataset.
# Engineered so biomarker_normal reads approximately normal WITH a real arm
# effect (-> ANOVA/Tukey find a difference), los_skewed is right-skewed
# (-> Kruskal-Wallis/Dunn), and responder is a Yes/No outcome whose rate rises
# with dose (-> chi-square association). 6 fixed rows have blank los_skewed to
# exercise missing-data handling. Rerunning MUST reproduce the committed
# artifacts byte-for-byte; if you change anything, bump GROUPCOMPARE_DEMO.version.
set.seed(59)
per <- 50
arm <- rep(c("Placebo", "Low dose", "High dose"), each = per)
arm_idx <- as.integer(factor(arm, levels = c("Placebo", "Low dose", "High dose")))
biomarker_normal <- round(rnorm(3 * per, mean = 40 + 6 * arm_idx, sd = 8), 1)
los_skewed <- round(rexp(3 * per, rate = 1 / (3 + arm_idx)) + 1, 1)  # right-skewed, >=1
resp_p <- c(0.25, 0.45, 0.7)[arm_idx]
responder <- ifelse(runif(3 * per) < resp_p, "Yes", "No")

miss_idx <- c(4, 33, 61, 88, 117, 140)
los_chr <- format(los_skewed, trim = TRUE)
los_chr[miss_idx] <- ""

out <- data.frame(arm = arm, biomarker_normal = biomarker_normal,
                  los_skewed = los_chr, responder = responder,
                  stringsAsFactors = FALSE)
write.csv(out, "tests/testthat/fixtures/groupcompare-demo.csv",
          row.names = FALSE, quote = FALSE)

rows_list <- lapply(seq_len(nrow(out)), function(i) {
  list(arm = arm[i], biomarker_normal = biomarker_normal[i],
       los_skewed = if (los_chr[i] == "") NA else los_skewed[i],
       responder = responder[i])
})
rows_json <- jsonlite::toJSON(rows_list, auto_unbox = TRUE, na = "null", digits = NA)
js <- paste0(
  "// GENERATED by data-raw/groupcompare-demo-generator.R — do not hand-edit.\n",
  "export const GROUPCOMPARE_DEMO = {\n",
  '  version: "1.0.0",\n',
  '  label: "Synthetic demonstration data",\n',
  '  columns: ["arm", "biomarker_normal", "los_skewed", "responder"],\n',
  "  rows: ", rows_json, "\n};\n")
writeLines(js, "web/guided/groupcompare/demo-data.js")
cat("md5(csv):", unname(tools::md5sum("tests/testthat/fixtures/groupcompare-demo.csv")), "\n")
