# data-raw/km-demo-generator.R
# Deterministic generator for the frozen KM Demonstration Dataset.
# Seed 23 is verified against the pinned teaching targets (see test-km-demo.R).
# Rerunning MUST reproduce the committed artifacts byte-for-byte; if you change
# anything here, bump KM_DEMO.version and re-pin every expected value.
set.seed(23)
n <- 60
t_std <- rexp(n, rate = log(2) / 26)
t_new <- rexp(n, rate = log(2) / 40)
drop_std <- rexp(n, rate = log(2) / 70)
drop_new <- rexp(n, rate = log(2) / 70)
admin_std <- runif(n, 24, 36)
admin_new <- runif(n, 24, 36)
time_std <- pmin(t_std, drop_std, admin_std)
time_new <- pmin(t_new, drop_new, admin_new)
df <- data.frame(
  followup_months = round(c(time_std, time_new), 1),
  event = c(as.integer(t_std <= pmin(drop_std, admin_std)),
            as.integer(t_new <= pmin(drop_new, admin_new))),
  group = rep(c("Standard care", "New treatment"), each = n))
df$followup_months[df$followup_months < 0.1] <- 0.1
out <- data.frame(
  participant_id = sprintf("P%03d", seq_len(nrow(df))),
  followup_months = df$followup_months,
  status = ifelse(df$event == 1, "Death", "Censored"),
  group = df$group)
write.csv(out, "tests/testthat/fixtures/km-demo.csv", row.names = FALSE, quote = FALSE)

rows_json <- jsonlite::toJSON(out, dataframe = "rows", digits = NA)
js <- paste0(
  "// GENERATED by data-raw/km-demo-generator.R — do not hand-edit.\n",
  "export const KM_DEMO = {\n",
  '  version: "1.0.0",\n',
  '  label: "Synthetic demonstration data",\n',
  '  columns: ["participant_id", "followup_months", "status", "group"],\n',
  "  rows: ", rows_json, "\n};\n")
writeLines(js, "web/guided/km/demo-data.js")
cat("md5(csv):", unname(tools::md5sum("tests/testthat/fixtures/km-demo.csv")), "\n")
