# data-raw/linear-demo-generator.R
# Frozen linear-regression demo. Continuous outcome `los` (hospital length of
# stay, days), two arms (Standard care / New treatment), baseline age and ordinal
# stage (I/II/III). Engineered so age + stage confound the arm effect: the
# UNADJUSTED arm coefficient is near 0, but adjusting reveals a ~1.5-day shorter
# stay. Byte-reproducible; bump LINEAR_DEMO.version on any change.
#
# Retuning guide. The teaching point is the gap between the crude and adjusted
# arm coefficient, set by: how much older / later-stage the New treatment arm is
# (age shift and the two stage probability vectors); how strongly age and stage
# drive `los` (0.08 and 1.5 below); and the true treatment effect (-1.5). The
# verification block at the end stops the script unless the story holds AND the
# default model is quiet on the residual advisories; if it stops, change the
# seed, never the assertions. Never hand-edit the generated outputs.
set.seed(31)
n_std <- 170
n_new <- 150
n <- n_std + n_new
arm <- c(rep("Standard care", n_std), rep("New treatment", n_new))
treated <- arm == "New treatment"

age <- round(rnorm(n, 60, 9))
age <- round(age + 6 * treated)
stage <- ifelse(treated,
  sample(c("I", "II", "III"), n, replace = TRUE, prob = c(0.22, 0.35, 0.43)),
  sample(c("I", "II", "III"), n, replace = TRUE, prob = c(0.55, 0.32, 0.13)))
stage_idx <- as.integer(factor(stage, levels = c("I", "II", "III")))

los <- 6 + 0.08 * (age - 60) + 1.5 * (stage_idx - 1) - 1.5 * treated + rnorm(n, 0, 2.2)
los <- round(pmax(los, 1), 1)

out <- data.frame(arm = arm, age = age, stage = stage, los = los,
                  stringsAsFactors = FALSE)

# ---- verification: the story the Understand/Example copy tells must hold.
dat <- out
dat$arm <- stats::relevel(factor(dat$arm), ref = "Standard care")
dat$stage <- factor(dat$stage)
crude <- stats::confint(stats::lm(los ~ arm, data = dat))["armNew treatment", ]
fit <- stats::lm(los ~ arm + age + stage, data = dat)
adj <- stats::confint(fit)["armNew treatment", ]
stopifnot(crude[1] < 0, crude[2] > 0)     # crude CI straddles 0
stopifnot(adj[2] < 0)                      # adjusted CI entirely below 0
stopifnot(stats::shapiro.test(stats::resid(fit))$p.value > 0.10)
aux <- stats::lm(stats::resid(fit)^2 ~ stats::fitted(fit))
bp <- nrow(dat) * summary(aux)$r.squared
stopifnot(stats::pchisq(bp, df = 1, lower.tail = FALSE) > 0.10)
cat(sprintf("crude arm: %.2f to %.2f; adjusted arm: %.2f to %.2f\n",
            crude[1], crude[2], adj[1], adj[2]))

stopifnot(!any(grepl('[",\r\n]', unlist(lapply(out, as.character)))))
write.csv(out, "tests/testthat/fixtures/linear-demo.csv",
          row.names = FALSE, quote = FALSE)

rows_list <- lapply(seq_len(nrow(out)), function(i) as.list(out[i, ]))
rows_json <- jsonlite::toJSON(rows_list, auto_unbox = TRUE, digits = NA)
js <- paste0(
  "// GENERATED by data-raw/linear-demo-generator.R — do not hand-edit.\n",
  "export const LINEAR_DEMO = {\n",
  '  version: "1.0.0",\n',
  '  label: "Synthetic demonstration data",\n',
  '  columns: ["arm", "age", "stage", "los"],\n',
  "  rows: ", rows_json, "\n};\n")
dir.create("web/guided/linear", showWarnings = FALSE)
writeLines(js, "web/guided/linear/demo-data.js")
cat("md5(csv):", unname(tools::md5sum("tests/testthat/fixtures/linear-demo.csv")), "\n")
