# data-raw/logistic-demo-generator.R
# Frozen logistic-regression demo. Binary outcome `complication` (Yes/No), two
# arms (Standard care / New treatment), baseline age and ordinal stage (I/II/III).
# Engineered so age + stage confound the arm effect: the UNADJUSTED arm OR is near
# 1, but adjusting reveals a protective adjusted OR (~0.5). Byte-reproducible;
# bump LOGISTIC_DEMO.version on any change.
#
# Retuning guide. The teaching point is the gap between the crude and adjusted
# arm OR, and it is set by three knobs:
#   * how much older / later-stage the New treatment arm is (age_shift and the
#     two stage probability vectors) — more channelling pushes the UNADJUSTED OR
#     up towards (and past) 1;
#   * how strongly age and stage drive the outcome (0.07 and 0.70 in `lp`) — same
#     direction as above;
#   * the true treatment effect (the -1.0 arm term) — more negative pushes the
#     ADJUSTED OR down.
# `n_std`/`n_new` are deliberately unequal and stage I is the most common level,
# so the app's default reference levels (most frequent level) land on
# "Standard care" and "I" even if a caller passes no ref_levels.
# Retune the coefficients before touching the seed, and re-run the verification
# in the task brief after any change. Never hand-edit the generated outputs.
set.seed(72)
n_std <- 170
n_new <- 150
n <- n_std + n_new
arm <- c(rep("Standard care", n_std), rep("New treatment", n_new))
treated <- arm == "New treatment"

age <- round(rnorm(n, 60, 9))
# Channelling by indication: clinicians reserve the new treatment for older,
# later-stage patients, which is exactly what makes the crude comparison lie.
age <- round(age + 6 * treated)
stage <- ifelse(treated,
  sample(c("I", "II", "III"), n, replace = TRUE, prob = c(0.22, 0.35, 0.43)),
  sample(c("I", "II", "III"), n, replace = TRUE, prob = c(0.55, 0.32, 0.13)))
stage_idx <- as.integer(factor(stage, levels = c("I", "II", "III")))

lp <- -1.4 + 0.07 * (age - 60) + 0.70 * (stage_idx - 1) - 1.0 * treated
complication <- ifelse(runif(n) < plogis(lp), "Yes", "No")

out <- data.frame(arm = arm, age = age, stage = stage,
                  complication = complication, stringsAsFactors = FALSE)

# quote = FALSE is only safe while every value is a bare word, a Roman numeral or
# an integer age. Fail loudly rather than write a corrupt CSV if that changes.
stopifnot(!any(grepl('[",\r\n]', unlist(lapply(out, as.character)))))
write.csv(out, "tests/testthat/fixtures/logistic-demo.csv",
          row.names = FALSE, quote = FALSE)

rows_list <- lapply(seq_len(nrow(out)), function(i) as.list(out[i, ]))
rows_json <- jsonlite::toJSON(rows_list, auto_unbox = TRUE, digits = NA)
js <- paste0(
  "// GENERATED by data-raw/logistic-demo-generator.R — do not hand-edit.\n",
  "export const LOGISTIC_DEMO = {\n",
  '  version: "1.0.0",\n',
  '  label: "Synthetic demonstration data",\n',
  '  columns: ["arm", "age", "stage", "complication"],\n',
  "  rows: ", rows_json, "\n};\n")
writeLines(js, "web/guided/logistic/demo-data.js")
cat("md5(csv):", unname(tools::md5sum("tests/testthat/fixtures/logistic-demo.csv")), "\n")
