# data-raw/summary-demo-generator.R
# Deterministic generator for the frozen Summary (Table 1) demonstration dataset.
# Engineered so age reads approximately normal (-> mean ± SD) while length_of_stay
# and crp are right-skewed (-> median (IQR)), with exactly 8 missing length_of_stay
# values to exercise missing-data reporting. Rerunning MUST reproduce the committed
# artifacts byte-for-byte; if you change anything here, bump SUMMARY_DEMO.version
# and re-check the teaching targets in tests/testthat/test-summary-demo.R.
set.seed(41)
n <- 60  # per arm; 120 total
arm <- rep(c("Control", "Treatment"), each = n)
age <- round(rnorm(2 * n, mean = 58, sd = 11))
length_of_stay <- round(rexp(2 * n, rate = 1 / 5) + 1, 1)   # right-skewed, >= 1 day
crp <- round(rlnorm(2 * n, meanlog = 1.6, sdlog = 0.9), 1)  # right-skewed biomarker
sex <- sample(c("Female", "Male"), 2 * n, replace = TRUE)
diabetes <- sample(c("No", "Yes"), 2 * n, replace = TRUE, prob = c(0.7, 0.3))

# Deterministic missingness: 8 fixed rows have unknown length of stay.
miss_idx <- c(3, 17, 24, 38, 51, 66, 89, 104)
los_chr <- format(length_of_stay, trim = TRUE)
los_chr[miss_idx] <- ""   # empty cell in the CSV -> null in JS

out <- data.frame(
  age = age,
  length_of_stay = los_chr,
  crp = crp,
  sex = sex,
  diabetes = diabetes,
  arm = arm,
  stringsAsFactors = FALSE)
write.csv(out, "tests/testthat/fixtures/summary-demo.csv", row.names = FALSE, quote = FALSE)

# JS module: emit length_of_stay as null where the CSV cell is empty.
rows_list <- lapply(seq_len(nrow(out)), function(i) {
  list(age = age[i],
       length_of_stay = if (los_chr[i] == "") NA else length_of_stay[i],
       crp = crp[i], sex = sex[i], diabetes = diabetes[i], arm = arm[i])
})
rows_json <- jsonlite::toJSON(rows_list, auto_unbox = TRUE, na = "null", digits = NA)
js <- paste0(
  "// GENERATED by data-raw/summary-demo-generator.R — do not hand-edit.\n",
  "export const SUMMARY_DEMO = {\n",
  '  version: "1.0.0",\n',
  '  label: "Synthetic demonstration data \\u2014 not for clinical use.",\n',
  '  columns: ["age", "length_of_stay", "crp", "sex", "diabetes", "arm"],\n',
  "  rows: ", rows_json, "\n};\n")
writeLines(js, "web/guided/summary/demo-data.js")
cat("md5(csv):", unname(tools::md5sum("tests/testthat/fixtures/summary-demo.csv")), "\n")
