# Script-builder helpers (R/script.R). The generated script must parse and,
# when evaluated in a clean environment, reproduce the embedded data.

script_spec <- function(...) list(
  data = list(list(a = "1", b = "x"), list(a = "2.5", b = "y"),
              list(a = "4", b = "")),
  options = list(...))

test_that("embedded-data script parses and rebuilds the data frame", {
  code <- .script_assemble("Test analysis", script_spec(), c("a", "b"),
                           character(0), c("m <- mean(df$a)"))
  expect_match(code, "R script generated by Figura", fixed = TRUE)
  expect_match(code, "example data (embedded in this script)", fixed = TRUE)
  expect_match(code, R.version.string, fixed = TRUE)
  env <- new.env(parent = globalenv())
  eval(parse(text = code), env)
  expect_equal(env$df$a, c(1, 2.5, 4))       # numeric column detected
  expect_equal(env$df$b, c("x", "y", NA))    # blank cell -> NA
  expect_equal(env$m, 2.5)
})

test_that("source_filename switches to read.csv and embeds nothing", {
  code <- .script_assemble("Test analysis",
                           script_spec(source_filename = "my data.csv"),
                           c("a", "b"), character(0), "nrow(df)")
  expect_match(code, 'read.csv("my data.csv", check.names = FALSE)', fixed = TRUE)
  expect_false(grepl("data.frame(", code, fixed = TRUE))
  expect_match(code, "# Data: my data.csv", fixed = TRUE)
})

test_that("header lists package versions and .script_fun embeds source", {
  h <- .script_header("X", "y.csv", "ggplot2")
  expect_match(paste(h, collapse = "\n"),
               sprintf("ggplot2 %s", utils::packageVersion("ggplot2")), fixed = TRUE)
  f <- .script_fun(".fmt_num", .fmt_num)
  env <- new.env(parent = globalenv())
  eval(parse(text = paste(f, collapse = "\n")), env)
  expect_equal(env$.fmt_num(1.125), .fmt_num(1.125))
})
