// scripts/pages/html.mjs — pure string templates for the generated pages.
import { SITE, CITATION, BIBTEX } from "./registry.mjs";

export function escapeHtml(s) {
  return String(s).replace(/&/g, "&amp;").replace(/</g, "&lt;")
    .replace(/>/g, "&gt;").replace(/"/g, "&quot;");
}

// One <head> for every page. Relative asset paths (../) keep the pages
// subpath-safe, the same reason sw.js resolves against its scope.
function head({ title, description, canonical }) {
  const t = escapeHtml(`${title} — Figura`);
  const d = escapeHtml(description);
  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${t}</title>
<meta name="description" content="${d}">
<link rel="canonical" href="${canonical}">
<meta property="og:type" content="website">
<meta property="og:site_name" content="Figura">
<meta property="og:url" content="${canonical}">
<meta property="og:title" content="${t}">
<meta property="og:description" content="${d}">
<meta property="og:image" content="${SITE}/preview.png">
<meta property="og:image:type" content="image/png">
<meta property="og:image:width" content="1200">
<meta property="og:image:height" content="630">
<meta property="og:image:alt" content="Figura: real R, running in your browser — beside a journal-style Table 1 of baseline characteristics.">
<meta name="twitter:card" content="summary_large_image">
<link rel="stylesheet" href="../styles.css">
<link rel="stylesheet" href="../pages.css">
</head>`;
}

// nav = [{href, label, current}] — rendered on every page.
function pageNav(nav) {
  return `<nav class="page-nav" aria-label="Site">` + nav.map((n) =>
    `<a href="${n.href}"${n.current ? ' aria-current="page"' : ""}>${escapeHtml(n.label)}</a>`
  ).join("") + `</nav>`;
}

function masthead() {
  return `<header class="toolbar"><a class="wordmark" href="../">Figura</a></header>`;
}

function citeBlock() {
  return `<section class="cite" id="cite">
<h2>How to cite</h2>
<p>Journals ask for a software statement. The methods text Figura generates already ends with one; this is the same attribution in reference form.</p>
<pre>${escapeHtml(CITATION)}</pre>
<pre>${escapeHtml(BIBTEX)}</pre>
</section>`;
}

function foot(currentSlug) {
  const aboutLink = currentSlug === "about"
    ? "What the page does connect to, and why"
    : `<a href="../about/">What the page does connect to, and why</a>`;
  return `<footer class="doc-foot">
<p>Figura runs R in your browser via webR. There is no backend: your CSV and your results never leave the tab. ${aboutLink}.</p>
<p><a href="../validation.html">How the numbers are checked</a> · Feedback: feedback@figurastats.org</p>
</footer>`;
}

export function renderAnalysisPage(page, example, nav) {
  const canonical = `${SITE}/${page.slug}/`;
  const sections = page.sections.map((s) =>
    `<section><h2>${escapeHtml(s.title)}</h2>${s.html}</section>`).join("\n");
  const teaching = page.teachingVisual
    ? `<figure class="teaching-visual" aria-label="${escapeHtml(page.teachingVisual.alt)}">${page.teachingVisual.svg}<figcaption><strong>Illustration—not computed data.</strong></figcaption></figure>`
    : "";
  const isTable = /<table[\s>]/.test(example.svg);
  const exampleBlock = isTable
    ? `<figure>${example.svg}<figcaption>${escapeHtml(page.demo.label)}: the table Figura renders for the example dataset.</figcaption></figure>`
    : `<figure>${example.svg}<figcaption>${escapeHtml(page.demo.label)}: the figure Figura renders for the example dataset.</figcaption></figure>`;
  return `${head({ title: page.title, description: page.description, canonical })}
<body>
<div class="doc">
${masthead()}
${pageNav(nav)}
<article class="card">
<p class="eyebrow">Guided analysis</p>
<h1>${escapeHtml(page.title)}</h1>
<p class="lede">${escapeHtml(page.lede)}</p>
<div class="cta-row">
<a class="cta" href="../#${page.key}/example">See the worked example</a>
<a class="cta secondary" href="../#${page.key}/analyze">Analyze your data</a>
</div>
${sections}
${teaching}
<section class="example">
<h2>Example output</h2>
${exampleBlock}
${page.textKind === "code"
  ? `<p>The ggplot2 code Figura produced for this example — the exact call that drew the figure, ready to run in your own R session:</p>`
  : `<p>The text Figura produced for this example, ready to paste into a methods section:</p>`}
<pre class="example-text">${escapeHtml(example.text)}</pre>
</section>
<section>
<h2>Sample data</h2>
<p><a href="sample.csv" download>Download sample.csv</a> — ${page.demo.rows.length} rows, columns <code>${page.demo.columns.map(escapeHtml).join("</code>, <code>")}</code>. A frozen synthetic dataset generated by a script in the repository's <code>data-raw/</code> folder; nothing in it is a real patient.</p>
</section>
${citeBlock()}
</article>
${foot(page.slug)}
</div>
</body>
</html>
`;
}

export function renderAboutPage(nav) {
  const canonical = `${SITE}/about/`;
  return `${head({ title: "About", description: "What Figura is, whether you can use it with patient data, what the page connects to, how the numbers are checked, and how to cite it.", canonical })}
<body>
<div class="doc">
${masthead()}
${pageNav(nav)}
<article class="card">
<p class="eyebrow">About</p>
<h1>About Figura</h1>
<p class="lede">Figura makes journal-ready tables and figures for clinical manuscripts: a Table 1, Kaplan–Meier curves, group comparisons, Cox and logistic regression tables, and ggplot2 figures. Real R packages do the statistics, running inside your browser through webR. It is free, and it has no server.</p>

<h2>Can I use this with patient data?</h2>
<p><strong>Your data stays in the tab.</strong> There is no backend, no upload, and no request that carries any part of your CSV or any result. R runs in a Web Worker in your browser; the figures you download are produced there.</p>
<p><strong>What the page does connect to.</strong> Three things, and nothing else:</p>
<ul>
<li>the webR runtime and R packages, downloaded from the webR content delivery network the first time you run an analysis;</li>
<li>Figura's own files from this domain: the app, the R sources, self-hosted fonts;</li>
<li>Cloudflare Web Analytics, a small beacon Cloudflare injects at the network edge. It reports that a page loaded, the referring site, country, device type and browser to Cloudflare. It carries no uploaded research data and no analysis results; nothing from your files is in it. You can see it in your browser's network panel as a request to <code>/cdn-cgi/rum</code>.</li>
</ul>
<p>You can verify all of this yourself: open the browser's developer tools, watch the network panel while you run an analysis, and confirm that no request leaves with your data.</p>

<h2>How the numbers are checked</h2>
<p>Every statistic Figura reports on eight fixed test datasets is re-derived by an independent Python implementation written from a specification rather than from Figura's R, and every difference is published. <a href="../validation.html">Read the validation page</a>.</p>

${citeBlock()}

<h2>Feedback</h2>
<p>Write to feedback@figurastats.org. Bugs, ideas, and analyses you wish it had are all welcome.</p>

<h2>The analyses</h2>
<ul>
${nav.filter((n) => n.slug).map((n) => `<li><a href="${n.href}">${escapeHtml(n.label)}</a></li>`).join("\n")}
</ul>
</article>
${foot("about")}
</div>
</body>
</html>
`;
}

export function renderSitemap(urls) {
  return `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${urls.map((u) => `  <url><loc>${u}</loc></url>`).join("\n")}
</urlset>
`;
}

export function renderRobots() {
  return `User-agent: *\nAllow: /\nSitemap: ${SITE}/sitemap.xml\n`;
}
