# R/script.R
# Builders for the downloadable per-analysis R script (the optional `code`
# field of a fig_* result). The statistical calls in each script are deparsed
# from the SAME expressions the fig_* function evaluated, so the numbers a
# user reproduces in their own R session match by construction.
# Spec: docs/superpowers/specs/2026-07-16-r-code-export-design.md

# Deparse one expression/call at 60 columns with two-space continuations.
.script_dep <- function(e) paste(deparse(e, width.cutoff = 60L), collapse = "\n  ")

# ---- Citation ----------------------------------------------------------------
# ONE place to change when a DOI is minted: swap FIGURA_CITE_URL for the DOI URL.
# The sentence deliberately carries NO R version and NO date. The webR release
# gate (stats-validation, `make webr`) compares displayed sentences between
# native R and webR line by line; a version would differ between them and a
# date would change daily. R.version.string already lives in .script_header.
FIGURA_CITE_AUTHOR <- "Saha"
FIGURA_CITE_YEAR   <- "2026"
FIGURA_CITE_URL    <- "https://figurastats.org"

# The attribution sentence a manuscript's methods section needs. `pkgs` is the
# same vector the analysis hands .script_assemble, so the sentence and the
# script header name the same packages.
.citation_sentence <- function(pkgs = character(0)) {
  pkgs <- as.character(pkgs)
  n <- length(pkgs)
  runs <- if (n == 0) {
    "which runs R in the browser"
  } else if (n == 1) {
    sprintf("which runs R with the %s package in the browser", pkgs)
  } else if (n == 2) {
    sprintf("which runs R with the %s and %s packages in the browser", pkgs[1], pkgs[2])
  } else {
    sprintf("which runs R with the %s, and %s packages in the browser",
            paste(pkgs[-n], collapse = ", "), pkgs[n])
  }
  sprintf("Analyses were performed with Figura (%s, %s; %s), %s.",
          FIGURA_CITE_AUTHOR, FIGURA_CITE_YEAR, FIGURA_CITE_URL, runs)
}

# Append the sentence as the FINAL paragraph of a methods text. The blank line
# is load-bearing: the validation comparator strips exactly one trailing
# paragraph that matches the sentence (stats-validation/compare/compare.py,
# strip_citation), and the spec/*.md files document that rule.
.with_citation <- function(text, pkgs = character(0))
  paste0(text, "\n\n", .citation_sentence(pkgs))

# Embed one of the app's own helper functions into the script, source and all,
# so effect sizes in the user's session are the app's own computation.
.script_fun <- function(name, fn)
  c(paste0(name, " <- ", paste(deparse(fn), collapse = "\n")), "")

# Header comment block: analysis, data source, honesty line, versions. The
# honesty line defaults to the exact-calls wording; analyses whose script
# parallel-reconstructs (rather than deparses evaluated calls) pass their own.
.script_header <- function(analysis, source_label, pkgs = character(0),
                           honesty = c(
                             "# The statistical calls below are the exact calls the app ran; the plot",
                             "# code produces an equivalent (not pixel-identical) figure.")) {
  pkg_lines <- vapply(pkgs, function(p)
    sprintf("#   %s %s", p, as.character(utils::packageVersion(p))), character(1))
  c(sprintf("# %s — R script generated by Figura", analysis),
    sprintf("# Data: %s", source_label),
    sprintf("# Cite: %s", .citation_sentence(pkgs)),
    honesty,
    paste0("# ", R.version.string),
    if (length(pkg_lines) > 0) c("# Package versions:", pkg_lines),
    "")
}

# Data section. A spec carrying options$source_filename reads that file (the
# NAME travels, never the contents); otherwise — demo runs — the used columns
# are embedded as a data.frame literal so the script runs as-is.
# Returns list(lines = <character>, source_label = <character(1)>).
#
# THE THREE READ LINES ARE A PARITY CONTRACT, not a convenience. The app never
# calls read.csv: it parses the CSV in the browser with parseCsv (web/lib/csv.js),
# which trims every cell and calls a cell missing only when it is empty AFTER
# trimming — so the two-character text "NA" is an ordinary value there. Plain
# read.csv disagrees three ways (na.strings = "NA" eats the literal; whitespace-
# only cells survive; padded text becomes a second, phantom factor level), and a
# script that disagrees analyses a different study than the table on screen. Each
# emitted line closes one of those, and they must stay in this order: read
# without na.strings, THEN trim, THEN call what is left empty missing — trimming
# after the blank check would leave " " behind as a value.
# See stats-validation/issues/02-app-vs-exported-script-missing-values.md.
# Numeric columns need no trimming: read.table always strips whitespace from a
# numeric field and reads a blank one as NA, which is parseCsv's answer too.
.script_data <- function(spec, cols) {
  fn <- as.character(spec$options$source_filename %||% "")
  if (nzchar(fn)) {
    return(list(
      lines = c("# Place this script in the same folder as your CSV. These three lines",
                "# read it exactly the way the app read it: text that reads \"NA\" is kept",
                "# as the value \"NA\", spaces around a cell are trimmed off, and a cell",
                "# that is empty after trimming counts as missing.",
                sprintf('df <- read.csv("%s", check.names = FALSE, na.strings = character(0))',
                        gsub('"', '\\\\"', fn)),
                "df[] <- lapply(df, function(x) if (is.character(x)) trimws(x) else x)",
                'df[df == ""] <- NA', ""),
      source_label = fn))
  }
  # The embedded branch needs no parity lines and must not grow any: its cells
  # are spec$data, which ALREADY came through parseCsv (trimmed, blank-is-empty),
  # so it re-emits exactly what the app analysed. Re-trimming would be a no-op;
  # a literal "NA" fails the as.numeric test below, stays character, and deparses
  # back out as the quoted string "NA" — while a real NA deparses bare — so the
  # embedded literal round-trips the distinction the file branch had to restore.
  vecs <- lapply(cols, function(cl) {
    raw <- .char_col(spec$data, cl)
    raw[!is.na(raw) & raw == ""] <- NA
    num <- suppressWarnings(as.numeric(raw))
    if (!any(!is.na(raw) & is.na(num))) num else raw
  })
  names(vecs) <- cols
  df_call <- as.call(c(quote(data.frame), vecs,
                       list(check.names = FALSE, stringsAsFactors = FALSE)))
  list(lines = c("# Example data embedded so this script runs as-is:",
                 paste0("df <- ", .script_dep(df_call)), ""),
       source_label = "example data (embedded in this script)")
}

# Glue: header + data section + body, one string. `honesty` overrides the
# header's default exact-calls wording for analyses that parallel-reconstruct.
.script_assemble <- function(analysis, spec, cols, pkgs, body, honesty = NULL) {
  d <- .script_data(spec, cols)
  header <- if (is.null(honesty))
    .script_header(analysis, d$source_label, pkgs)
  else
    .script_header(analysis, d$source_label, pkgs, honesty = honesty)
  paste(c(header, d$lines, body, ""), collapse = "\n")
}
