# R/script.R
# Builders for the downloadable per-analysis R script (the optional `code`
# field of a fig_* result). The statistical calls in each script are deparsed
# from the SAME expressions the fig_* function evaluated, so the numbers a
# user reproduces in their own R session match by construction.
# Spec: docs/superpowers/specs/2026-07-16-r-code-export-design.md

# Deparse one expression/call at 60 columns with two-space continuations.
.script_dep <- function(e) paste(deparse(e, width.cutoff = 60L), collapse = "\n  ")

# Embed one of the app's own helper functions into the script, source and all,
# so effect sizes in the user's session are the app's own computation.
.script_fun <- function(name, fn)
  c(paste0(name, " <- ", paste(deparse(fn), collapse = "\n")), "")

# Header comment block: analysis, data source, honesty line, versions. The
# honesty line defaults to the exact-calls wording; analyses whose script
# parallel-reconstructs (rather than deparses evaluated calls) pass their own.
.script_header <- function(analysis, source_label, pkgs = character(0),
                           honesty = c(
                             "# The statistical calls below are the exact calls the app ran; the plot",
                             "# code produces an equivalent (not pixel-identical) figure.")) {
  pkg_lines <- vapply(pkgs, function(p)
    sprintf("#   %s %s", p, as.character(utils::packageVersion(p))), character(1))
  c(sprintf("# %s — R script generated by Figura", analysis),
    sprintf("# Data: %s", source_label),
    honesty,
    paste0("# ", R.version.string),
    if (length(pkg_lines) > 0) c("# Package versions:", pkg_lines),
    "")
}

# Data section. A spec carrying options$source_filename reads that file (the
# NAME travels, never the contents); otherwise — demo runs — the used columns
# are embedded as a data.frame literal so the script runs as-is.
# Returns list(lines = <character>, source_label = <character(1)>).
.script_data <- function(spec, cols) {
  fn <- as.character(spec$options$source_filename %||% "")
  if (nzchar(fn)) {
    return(list(
      lines = c("# Place this script in the same folder as your CSV:",
                sprintf('df <- read.csv("%s", check.names = FALSE)',
                        gsub('"', '\\\\"', fn)),
                'df[df == ""] <- NA   # blank cells are missing values', ""),
      source_label = fn))
  }
  vecs <- lapply(cols, function(cl) {
    raw <- .char_col(spec$data, cl)
    raw[!is.na(raw) & raw == ""] <- NA
    num <- suppressWarnings(as.numeric(raw))
    if (!any(!is.na(raw) & is.na(num))) num else raw
  })
  names(vecs) <- cols
  df_call <- as.call(c(quote(data.frame), vecs,
                       list(check.names = FALSE, stringsAsFactors = FALSE)))
  list(lines = c("# Example data embedded so this script runs as-is:",
                 paste0("df <- ", .script_dep(df_call)), ""),
       source_label = "example data (embedded in this script)")
}

# Glue: header + data section + body, one string. `honesty` overrides the
# header's default exact-calls wording for analyses that parallel-reconstruct.
.script_assemble <- function(analysis, spec, cols, pkgs, body, honesty = NULL) {
  d <- .script_data(spec, cols)
  header <- if (is.null(honesty))
    .script_header(analysis, d$source_label, pkgs)
  else
    .script_header(analysis, d$source_label, pkgs, honesty = honesty)
  paste(c(header, d$lines, body, ""), collapse = "\n")
}
